spring:
  # DB 접속 정보 설정
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.0.104:3306/eduDB
    username: root
    password: 1234
  # JPA 설정
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: b797d5ca119fb4404679bf5ef3c74bfef1f8a85cc3456d7da876c254b3ab8b5c

logging:
  level:
    root: DEBUG
    org:
      springframework:
        security: DEBUG
server:
  port: 8088
